FROM oven/bun:1.3.1 AS base
WORKDIR /app

FROM base AS install
RUN mkdir -p /temp/prod
COPY package.json bun.lock /temp/prod/
RUN cd /temp/prod && bun install --frozen-lockfile --production

FROM base AS release
WORKDIR /app

RUN addgroup --system bunuser && \
    adduser --system --ingroup bunuser bunuser

COPY --from=install --chown=bunuser:bunuser /temp/prod/node_modules node_modules

COPY --chown=bunuser:bunuser . .

USER bunuser

EXPOSE 3000

HEALTHCHECK --interval=10s --timeout=3s --start-period=30s --retries=3 \
  CMD bun --eval "await fetch('http://localhost:3000/v1/health').then(r => r.ok ? process.exit(0) : process.exit(1))" || exit 1

  
CMD ["bun", "run", "src/index.ts"]
